name: Run data assimilation (daily)
on:
  workflow_dispatch:
  schedule:
  - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
# Point to the right path, run the right Rscript command
      - name: Run daily forecast
        run: Rscript forecast_code/04_data_assimilation_v2.R 
